#Student Information (string)
club_name=input("Enter the club name: ")
print("Uppercase:",club_name.upper())
print("Lowercase:",club_name.lower())
print("Titlecase:",club_name.title())
old_word=input("Word to replace: ")
new_word=input("New word: ")
print("replace:",club_name.replace(old_word,new_word))
search_word=input("Enter word to find position: ")
print("Position:",club_name.find(search_word))
char=input("Enter the character to count: ")
print("count:",club_name.count(char))
start_letter=input("Enter the starting letter:")
print("startswith:",club_name.starswith(start_letter))
end_letter=input("Enter the ending letter: ")
print("endswith:",club_name.endswith(end_letter))
print("Split words:",club_name.split())
print("After Strip:",club_name.strip())

#Club activities (tuple)
print("First Activity:",activities[0])
print("Last Activity:",activities[-1])
print("Activities from index 1 to 3:",activities[1:4])
print("Quiz appears:",activities.count("quiz"),)


